spring:
  application:
    name: desgin
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: 30MB
  profiles:
    active: dev

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: auto

server:
  port: 8081
  servlet:
    context-path: /detector

deepfake:
  rq:
    email:
      queue: deepfake.email.queue
    record:
      queue: deepfake.record.queue
      deleteQueue: deepfake.record.deleteQueue
    redis:
      queue: deepfake.redis.queue
  ex: deepfake.ex
rabbitmq:
  params:
    split: ;;;
redis:
  expireTime: 1800

oss:
  server:
    url:
      prefix: https://deepfakedetector.oss-cn-hangzhou.aliyuncs.com/