logging:
  level:
    root: info
    com.coder.design.controller: trace
  pattern:
    console: "%d{yyyy-MM-dd} ---- %-5level [%thread] %logger{10}:%msg%n"
  file:
    path: E:\\code\\github\\desgin\\mylog
    name: E:\\code\\github\\desgin\\mylog\\design.log

spring:
  mail:
    host: smtp.qq.com
    username: 1023668958@qq.com
    password: flujtaexoaulbbda
  redis:
    host: 106.15.176.6
    port: 6379
    password: 123456
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-wait: 5000