logging:
  level:
    root: info
    com.coder.design.controller: trace
  pattern:
    console: "%d{yyyy-MM-dd} ---- %-5level [%thread] %logger{10}:%msg%n"
  file:
    path: E:\\code\\github\\bs\\DeepFake\\desgin\\mylog
    name: E:\\code\\github\\bs\\DeepFake\\desgin\\mylog\\design.log

spring:
  mail:
    host: smtp.qq.com
    username: ${QQ_EMAIL}
    password: ${QQ_EMAIL_PWD}
  redis:
    host: ${REDIS_HOST}
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWD}
    timeout: 5000
    database: 0
    lettuce:
      pool:
        max-wait: 5000